server: 
  port: 56081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:56080/eureka/

spring:
  ##################### DB #####################
  datasource:
    ds0:
      url: jdbc:mysql://localhost:3306/bank1?useUnicode=true
      username: root
      password: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT user()
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      connection-properties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000


#  cloud:
#   alibaba:
#      seata:
#        tx-service-group: seata-demo-bank1-fescar-service-group

logging:
  level:
    root: INFO
    io:
      seata: DEBUG
    org:
      springframework:
        cloud:
          alibaba:
            seata:
              web: DEBUG


